# Generated by Django 5.0.14 on 2026-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('pro', 'Pro'), ('business', 'Business')], default='pro', max_length=20),
        ),
    ]
