# Generated by Django 5.0.14 on 2026-04-05 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms and Conditions'), ('cookie', 'Cookie Policy'), ('disclaimer', 'Disclaimer'), ('refund', 'Refund Policy')], max_length=20)),
                ('company_name', models.CharField(default='My Company', max_length=200)),
                ('website_url', models.URLField(blank=True, default='')),
                ('contact_email', models.EmailField(default='hello@example.com', max_length=254)),
                ('industry', models.CharField(choices=[('saas', 'SaaS / Web App'), ('ecommerce', 'E-Commerce / Online Store'), ('mobile', 'Mobile App'), ('blog', 'Blog / Content'), ('marketplace', 'Marketplace / Platform'), ('consulting', 'Consulting'), ('healthcare', 'Healthcare'), ('finance', 'Finance / Fintech'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=20)),
                ('regulations', models.JSONField(blank=True, default=list)),
                ('has_third_party', models.BooleanField(default=False)),
                ('has_user_accounts', models.BooleanField(default=False)),
                ('has_cookies', models.BooleanField(default=False)),
                ('has_payments', models.BooleanField(default=False)),
                ('has_newsletter', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('content', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('updated', 'Updated')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
