# Generated by Django 5.0.14 on 2026-04-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('score', models.IntegerField(help_text='0-100 compliance score')),
                ('issues_found', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('has_privacy_policy', models.BooleanField(default=False)),
                ('has_terms', models.BooleanField(default=False)),
                ('has_cookie_policy', models.BooleanField(default=False)),
                ('gdpr_compliant', models.BooleanField(default=False)),
                ('ccpa_compliant', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default='', help_text='Optional — send them results', max_length=254)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_score',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('saas', 'SaaS / Web App'), ('ecommerce', 'E-Commerce / Online Store'), ('mobile', 'Mobile App'), ('blog', 'Blog / Content'), ('marketplace', 'Marketplace / Platform'), ('consulting', 'Consulting'), ('healthcare', 'Healthcare'), ('finance', 'Finance / Fintech'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=50)),
                ('regulation', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('meta_description', models.TextField(default='')),
                ('h1', models.CharField(max_length=200)),
                ('intro', models.TextField(default='')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('cta_text', models.CharField(default='Generate your privacy policy', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seo_landing_page',
                'ordering': ['-created_at'],
            },
        ),
    ]
